package enums;

import java.util.Collections;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor(access = AccessLevel.PRIVATE)
@Getter
public enum Champions {

	AATROX("Aatrox", Gender.MALE, newSingleton(Position.TOP),
			newSingleton(Species.DARKIN), Resource.MANALESS,
			newSingleton(RangeType.MELEE),
			newSet(Region.RUNETERRA, Region.SHURIMA), 2013),
	AHRI("Ahri", Gender.FEMALE, newSingleton(Position.MIDDLE),
			newSingleton(Species.VASTAYAN), Resource.MANA,
			newSingleton(RangeType.RANGED), newSingleton(Region.IONIA), 2011),
	AKALI("Akali", Gender.FEMALE, newSet(Position.MIDDLE, Position.TOP),
			newSingleton(Species.HUMAN), Resource.ENERGY,
			newSingleton(RangeType.MELEE), newSingleton(Region.IONIA), 2010),
	AKSHAN("Akshan", Gender.MALE, newSet(Position.MIDDLE, Position.TOP),
			newSingleton(Species.HUMAN), Resource.MANA,
			newSingleton(RangeType.RANGED), newSingleton(Region.SHURIMA), 2021),
	ALISTAR("Alistar", Gender.MALE, newSingleton(Position.SUPPORT),
			newSingleton(Species.MINOTAUR), Resource.MANA,
			newSingleton(RangeType.MELEE), newSingleton(Region.RUNETERRA),
			2009),
	AMUMU("Amumu", Gender.MALE, newSet(Position.JUNGLE, Position.SUPPORT),
			newSet(Species.UNDEAD, Species.YORDLE), Resource.MANA,
			newSingleton(RangeType.MELEE), newSingleton(Region.SHURIMA), 2009),
	ANIVIA("Anivia", Gender.FEMALE, newSingleton(Position.MIDDLE),
			newSet(Species.GOD, Species.SPIRIT), Resource.MANA,
			newSingleton(RangeType.RANGED), newSingleton(Region.FRELJORD),
			2009),
	ANNIE("Annie", Gender.FEMALE, newSingleton(Position.MIDDLE),
			newSet(Species.HUMAN, Species.MAGICBORN), Resource.MANA,
			newSingleton(RangeType.RANGED),
			newSet(Region.NOXUS, Region.RUNETERRA), 2009),
	APHELIOS("Aphelios", Gender.MALE, newSingleton(Position.BOTTOM),
			newSet(Species.HUMAN, Species.SPIRITUALIST), Resource.MANA,
			newSingleton(RangeType.RANGED), newSingleton(Region.TARGON), 2019),
	ASHE("Ashe", Gender.FEMALE, newSet(Position.BOTTOM, Position.SUPPORT),
			newSet(Species.HUMAN, Species.ICEBORN), Resource.MANA,
			newSingleton(RangeType.RANGED), newSingleton(Region.FRELJORD),
			2009),
	AURELION_SOL("Aurelion Sol", Gender.MALE, newSingleton(Position.MIDDLE),
			newSet(Species.CELESTIAL, Species.DRAGON), Resource.MANA,
			newSingleton(RangeType.RANGED),
			newSet(Region.RUNETERRA, Region.TARGON), 2016),
	AZIR("Azir", Gender.MALE, newSingleton(Position.MIDDLE),
			newSingleton(Species.GOD_WARRIOR), Resource.MANA,
			newSingleton(RangeType.RANGED), newSingleton(Region.SHURIMA), 2014),
	BARD("Bard", Gender.MALE, newSingleton(Position.SUPPORT),
			newSingleton(Species.CELESTIAL), Resource.MANA,
			newSingleton(RangeType.RANGED), newSingleton(Region.RUNETERRA),
			2015),
	BELVETH("Bel'Veth", Gender.FEMALE, newSingleton(Position.JUNGLE),
			newSingleton(Species.VOID_BEING), Resource.MANALESS,
			newSingleton(RangeType.MELEE), newSingleton(Region.VOID), 2022),
	BLITZCRANK("Blitzcrank", Gender.OTHER, newSingleton(Position.SUPPORT),
			newSingleton(Species.GOLEM), Resource.MANA,
			newSingleton(RangeType.MELEE), newSingleton(Region.ZAUN), 2009),
	BRAND(null, null, null, null, null, null, null, 0),
	BRAUM(null, null, null, null, null, null, null, 0),
	CAITLYN(null, null, null, null, null, null, null, 0),
	CAMILLE(null, null, null, null, null, null, null, 0),
	CASSIOPEIA(null, null, null, null, null, null, null, 0),
	CHOGATH(null, null, null, null, null, null, null, 0),
	CORKI(null, null, null, null, null, null, null, 0),
	DARIUS(null, null, null, null, null, null, null, 0),
	DIANA(null, null, null, null, null, null, null, 0),
	DR_MUNDO(null, null, null, null, null, null, null, 0),
	DRAVEN(null, null, null, null, null, null, null, 0),
	EKKO(null, null, null, null, null, null, null, 0),
	ELISE(null, null, null, null, null, null, null, 0),
	EVELYNN(null, null, null, null, null, null, null, 0),
	EZREAL(null, null, null, null, null, null, null, 0),
	FIDDLESTICKS(null, null, null, null, null, null, null, 0),
	FIORA(null, null, null, null, null, null, null, 0),
	FIZZ(null, null, null, null, null, null, null, 0),
	GALIO(null, null, null, null, null, null, null, 0),
	GANGPLANK(null, null, null, null, null, null, null, 0),
	GAREN(null, null, null, null, null, null, null, 0),
	GNAR(null, null, null, null, null, null, null, 0),
	GRAGAS(null, null, null, null, null, null, null, 0),
	GRAVES(null, null, null, null, null, null, null, 0),
	GWEN(null, null, null, null, null, null, null, 0),
	HECARIM(null, null, null, null, null, null, null, 0),
	HEIMERDINGER(null, null, null, null, null, null, null, 0),
	ILLAOI(null, null, null, null, null, null, null, 0),
	IRELIA(null, null, null, null, null, null, null, 0),
	IVERN(null, null, null, null, null, null, null, 0),
	JANNA(null, null, null, null, null, null, null, 0),
	JARVAN_IV(null, null, null, null, null, null, null, 0),
	JAX(null, null, null, null, null, null, null, 0),
	JAYCE(null, null, null, null, null, null, null, 0),
	JHIN(null, null, null, null, null, null, null, 0),
	JINX(null, null, null, null, null, null, null, 0),
	KSANTE(null, null, null, null, null, null, null, 0),
	KAISA(null, null, null, null, null, null, null, 0),
	KALISTA(null, null, null, null, null, null, null, 0),
	KARMA(null, null, null, null, null, null, null, 0),
	KARTHUS(null, null, null, null, null, null, null, 0),
	KASSADIN(null, null, null, null, null, null, null, 0),
	KATARINA(null, null, null, null, null, null, null, 0),
	KAYLE(null, null, null, null, null, null, null, 0),
	KAYN(null, null, null, null, null, null, null, 0),
	KENNEN(null, null, null, null, null, null, null, 0),
	KHAZIX(null, null, null, null, null, null, null, 0),
	KINDRED(null, null, null, null, null, null, null, 0),
	KLED(null, null, null, null, null, null, null, 0),
	KOGMAW(null, null, null, null, null, null, null, 0),
	LEBLANC(null, null, null, null, null, null, null, 0),
	LEE_SIN(null, null, null, null, null, null, null, 0),
	LEONA(null, null, null, null, null, null, null, 0),
	LILLIA(null, null, null, null, null, null, null, 0),
	LISSANDRA(null, null, null, null, null, null, null, 0),
	LUCIAN(null, null, null, null, null, null, null, 0),
	LULU(null, null, null, null, null, null, null, 0),
	LUX(null, null, null, null, null, null, null, 0),
	MALPHITE(null, null, null, null, null, null, null, 0),
	MALZAHAR(null, null, null, null, null, null, null, 0),
	MAOKAI(null, null, null, null, null, null, null, 0),
	MASTER_YI(null, null, null, null, null, null, null, 0),
	MISS_FORTUNE(null, null, null, null, null, null, null, 0),
	MORDEKAISER(null, null, null, null, null, null, null, 0),
	MORGANA(null, null, null, null, null, null, null, 0),
	NAMI(null, null, null, null, null, null, null, 0),
	NASUS(null, null, null, null, null, null, null, 0),
	NAUTILUS(null, null, null, null, null, null, null, 0),
	NEEKO(null, null, null, null, null, null, null, 0),
	NIDALEE(null, null, null, null, null, null, null, 0),
	NILAH(null, null, null, null, null, null, null, 0),
	NOCTURNE(null, null, null, null, null, null, null, 0),
	NUNU(null, null, null, null, null, null, null, 0),
	OLAF(null, null, null, null, null, null, null, 0),
	ORIANNA(null, null, null, null, null, null, null, 0),
	ORNN(null, null, null, null, null, null, null, 0),
	PANTHEON(null, null, null, null, null, null, null, 0),
	POPPY(null, null, null, null, null, null, null, 0),
	PYKE(null, null, null, null, null, null, null, 0),
	QIYANA(null, null, null, null, null, null, null, 0),
	QUINN(null, null, null, null, null, null, null, 0),
	RAKAN(null, null, null, null, null, null, null, 0),
	RAMMUS(null, null, null, null, null, null, null, 0),
	REKSAI(null, null, null, null, null, null, null, 0),
	RELL(null, null, null, null, null, null, null, 0),
	RENETA_GLASC(null, null, null, null, null, null, null, 0),
	RENEKTON(null, null, null, null, null, null, null, 0),
	RENGAR(null, null, null, null, null, null, null, 0),
	RIVEN(null, null, null, null, null, null, null, 0),
	RUMBLE(null, null, null, null, null, null, null, 0),
	RYZE(null, null, null, null, null, null, null, 0),
	SAMIRA(null, null, null, null, null, null, null, 0),
	SEJUANI(null, null, null, null, null, null, null, 0),
	SENNA(null, null, null, null, null, null, null, 0),
	SERAPHINE(null, null, null, null, null, null, null, 0),
	SETT(null, null, null, null, null, null, null, 0),
	SHACO(null, null, null, null, null, null, null, 0),
	SHEN(null, null, null, null, null, null, null, 0),
	SHYVANA(null, null, null, null, null, null, null, 0),
	SINGED(null, null, null, null, null, null, null, 0),
	SION(null, null, null, null, null, null, null, 0),
	SIVIR(null, null, null, null, null, null, null, 0),
	SKARNER(null, null, null, null, null, null, null, 0),
	SONA(null, null, null, null, null, null, null, 0),
	SORAKA(null, null, null, null, null, null, null, 0),
	SWAIN(null, null, null, null, null, null, null, 0),
	SYLAS(null, null, null, null, null, null, null, 0),
	SYNDRA(null, null, null, null, null, null, null, 0),
	TAHM_KENCH(null, null, null, null, null, null, null, 0),
	TALIYAH(null, null, null, null, null, null, null, 0),
	TALON(null, null, null, null, null, null, null, 0),
	TARIC(null, null, null, null, null, null, null, 0),
	TEEMO(null, null, null, null, null, null, null, 0),
	THRESH(null, null, null, null, null, null, null, 0),
	TRISTANA(null, null, null, null, null, null, null, 0),
	TRUNDLE(null, null, null, null, null, null, null, 0),
	TRYNDAMERE(null, null, null, null, null, null, null, 0),
	TWISTED_FATE(null, null, null, null, null, null, null, 0),
	TWITCH(null, null, null, null, null, null, null, 0),
	UDYR(null, null, null, null, null, null, null, 0),
	URGOT(null, null, null, null, null, null, null, 0),
	VARUS(null, null, null, null, null, null, null, 0),
	VAYNE(null, null, null, null, null, null, null, 0),
	VEIGAR(null, null, null, null, null, null, null, 0),
	VELKOZ(null, null, null, null, null, null, null, 0),
	VEX(null, null, null, null, null, null, null, 0),
	VI(null, null, null, null, null, null, null, 0),
	VIEGO(null, null, null, null, null, null, null, 0),
	VIKTOR(null, null, null, null, null, null, null, 0),
	VLADIMIR(null, null, null, null, null, null, null, 0),
	VOLIBEAR(null, null, null, null, null, null, null, 0),
	WARWICK(null, null, null, null, null, null, null, 0),
	WUKONG(null, null, null, null, null, null, null, 0),
	XAYAH(null, null, null, null, null, null, null, 0),
	XERATH(null, null, null, null, null, null, null, 0),
	XIN_ZHAO(null, null, null, null, null, null, null, 0),
	YASUO(null, null, null, null, null, null, null, 0),
	YONE(null, null, null, null, null, null, null, 0),
	YORICK(null, null, null, null, null, null, null, 0),
	YUUMI(null, null, null, null, null, null, null, 0),
	ZAC(null, null, null, null, null, null, null, 0),
	ZED(null, null, null, null, null, null, null, 0),
	ZERI(null, null, null, null, null, null, null, 0),
	ZIGGS(null, null, null, null, null, null, null, 0),
	ZILEAN(null, null, null, null, null, null, null, 0),
	ZOE(null, null, null, null, null, null, null, 0),
	ZYRA(null, null, null, null, null, null, null, 0);

	private final String championName;
	private final Gender gender;
	private final Set<Position> positions;
	private final Set<Species> species;
	private final Resource resource;
	private final Set<RangeType> rangeType;
	private final Set<Region> regions;
	private final int releaseYear;

	@SafeVarargs
	private static final <T> Set<T> newSet(T... objs) {
		return Stream.of(objs).collect(Collectors.toSet());
	}

	private static final <T> Set<T> newSingleton(T obj) {
		return Collections.singleton(obj);
	}

}
