package enums;

public enum Species {
    CELESTIAL, DARKIN, DRAGON, GOD, GOD_WARRIOR, GOLEM, HUMAN, ICEBORN,
    MAGICBORN, MINOTAUR, SPIRIT, SPIRITUALIST, UNDEAD, VASTAYAN, VOID_BEING,
    YORDLE;
}
