package enums;

import lombok.AccessLevel;
import lombok.AllArgsConstructor;

@AllArgsConstructor(access = AccessLevel.PRIVATE)
public enum Species {
    ASPECT, BRACKERN, CAT, CELESTIAL, CHEMICALLY_ALTERED, CYBORG, DARKIN, DEMON,
    DRAGON, GOD, GOD_WARRIOR, GOLEM, HUMAN, ICEBORN, MAGICALLY_ALTERED,
    MAGICBORN, MINOTAUR, RAT, REVENANT, SPIRIT, SPIRITUALIST, TROLL, UNDEAD,
    UNKNOWN, VASTAYAN, VOID_BEING, YETI, YORDLE;
}
